VimMerge実行時にscreenかtmuxが起動済みであれば別ウインドウでvimを立ち上げるようにした。

diff --git a/sh/VimMerge b/sh/VimMerge
--- a/sh/VimMerge
+++ b/sh/VimMerge
@@ -2,30 +2,69 @@
 
 command=`basename ${0}`
 diff_option=
-parent=`ps -U ${USER} | grep -e ${PPID} | grep -oe '[[:graph:]]\+$'`
+parent=`ps -U ${USER} | grep -m 1 -e ${PPID} | grep -oe '[[:graph:]]\+$'`
 case ${parent} in
 svn)
 	diff_option=${1}
 	while [ ${2} != -L ]; do diff_option="${diff_option} ${2}"; shift; done
 	target1=${6}
 	target2=${7}
-	sleep=1
+	parent_is_vcs=true
 	;;
 git)
 	target1=${2}
 	target2=${5}
-	sleep=1
+	parent_is_vcs=true
 	;;
 *)
 	target1=${1}
 	target2=${2}
-	sleep=
+	parent_is_vcs= # not set
 esac
 
-grep -qe '\.\(d\|o\|lo\|html\|jpg\|bdf\|gcda\|gcno\|info\|log\|xml\)$' <<EOF && echo Skipped: "'${target1}'" "'${target2}'" && exit 0
+grep -m 1 -qe '\.\(d\|o\|lo\|html\|jpg\|bdf\|gcda\|gcno\|info\|log\|xml\)$' <<EOF && echo Skipped: "'${target1}'" "'${target2}'" && exit 0
 ${target1}
 ${target2}
 EOF
+
+detect_multiplexer()
+{
+	ps -U ${USER} -o pid,ppid,comm | sed -e 1d | awk '
+	{
+		pids[$1]["ppid"]    = $2
+		pids[$1]["command"] = $3
+	}
+	END{
+		for(pid = '${PPID}'; pid != 1; pid = pids[pid]["ppid"]){
+			if(pids[pid]["command"] ~ /'${1}':?/){exit 0}
+		}
+		exit 1
+	}'
+}
+
+invoke_vim()
+{
+	which vim > /dev/null || { error_happened=true; return 1;}
+	vim --version | grep -m 1 -qe '+clientserver' || {
+		echo Error. Vim with "'clientserver'" feature is required, but your Vim does not have the feature... >&2
+		error_happened=true
+		return 1
+	}
+	vim --serverlist | grep -m 1 -qie ^${1}\$ || {
+		vim_setup_time=1
+		detect_multiplexer screen && screen vim --servername ${1} && sleep ${vim_setup_time} && return
+		detect_multiplexer tmux && tmux new-window vim --servername ${1} && sleep ${vim_setup_time} && return
+	} || {
+		cat <<-EOF >&2
+		Error. Vim server not found.
+		confirm that
+		  - Vim server '${1}' is running (Try again after to invoke vim '\$ vim --servername ${1}' on another tty)
+		  - X server is running (X11 forwarding is also enabled if via ssh)
+		EOF
+		error_happened=true
+		return 1
+	}
+}
 
 detect_filetype()
 {
@@ -42,36 +81,13 @@ detect_filetype()
 vim_diff()
 {
 	error_happened=
-	vim_servername=VIM
-	while getopts s: arg; do
-		case ${arg} in
-		s) vim_servername=${OPTARG};;
-		esac
-	done
-	shift `expr ${OPTIND} - 1`
-
-	trap '[ -n "${sleep}" -a -n "${error_happened}" ] && kill ${PPID}' EXIT
-	which vim > /dev/null || { error_happened=true; return 1;}
-	vim --version | grep -qe '+clientserver' || {
-		echo Error. Vim with "'clientserver'" feature is required, but your Vim does not have the feature... >&2
-		error_happened=true
-		return 1
-	}
-	vim --serverlist | grep -qe ^${vim_servername}\$ || {
-		cat <<-EOF >&2
-		Error. Vim server not found.
-		confirm that
-		  - Vim server '${vim_servername}' is running (Try again after to invoke vim '\$ vim --servername ${vim_servername}' on another tty)
-		  - X server is running (X11 forwarding is also enabled if via ssh)
-		EOF
-		error_happened=true
-		return 1
-	}
+	vim_servername=${command}
+	trap '[ -n "${parent_is_vcs}" -a -n "${error_happened}" ] && kill ${PPID}' EXIT
+	invoke_vim `echo ${vim_servername} | sed -e 's/^.\+$/\U&/'` || return
 
 	echo ${1} | grep -qe '^/tmp/svn-\|/\.svn/' && { tmp1=`mktemp --tmpdir ${command}.old.XXXXXX`; cp ${1} ${tmp1};}
 	echo ${2} | grep -qe '^/tmp/svn-\|/\.svn/' && { tmp2=`mktemp --tmpdir ${command}.new.XXXXXX`; cp ${2} ${tmp2};}
 	set ${tmp1:-${1}} ${tmp2:-${2}}
-
 	tmp_vimrc=`mktemp --tmpdir ${command}.vimrc.XXXXXX`
 	cat <<EOF > ${tmp_vimrc}
 set nocompatible
@@ -99,7 +115,6 @@ augroup ${command}
 augroup END
 EOF
 	vim --servername ${vim_servername} --remote-tab +"source ${tmp_vimrc}" /dev/null
-	[ -n "${sleep}" ] && sleep ${sleep}
 }
 
 invoke_diff()
